{
    "output": "",
    "errors": "...FF.\n======================================================================\nFAIL: test_case_4 (__main__.TestGetPermutation.test_case_4)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\60_permutation-sequence\\test.py\", line 35, in test_case_4\n    self.assertEqual(self.sol.getPermutation(5, 16), \"24135\")\nAssertionError: '14352' != '24135'\n- 14352\n+ 24135\n\n\n======================================================================\nFAIL: test_case_5 (__main__.TestGetPermutation.test_case_5)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\60_permutation-sequence\\test.py\", line 41, in test_case_5\n    self.assertEqual(self.sol.getPermutation(6, 400), \"341652\")\nAssertionError: '425361' != '341652'\n- 425361\n+ 341652\n\n\n----------------------------------------------------------------------\nRan 6 tests in 0.002s\n\nFAILED (failures=2)\n",
    "returncode": 1
}