{
    "output": "",
    "errors": "F..FFFFFF\n======================================================================\nFAIL: test_case_1 (__main__.TestNQueens.test_case_1)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 17, in test_case_1\n    self.assertEqual(self.solution.totalNQueens(1), 1)\nAssertionError: 0 != 1\n\n======================================================================\nFAIL: test_case_4 (__main__.TestNQueens.test_case_4)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 35, in test_case_4\n    self.assertEqual(self.solution.totalNQueens(4), 2)\nAssertionError: 0 != 2\n\n======================================================================\nFAIL: test_case_5 (__main__.TestNQueens.test_case_5)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 41, in test_case_5\n    self.assertEqual(self.solution.totalNQueens(5), 10)\nAssertionError: 0 != 10\n\n======================================================================\nFAIL: test_case_6 (__main__.TestNQueens.test_case_6)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 47, in test_case_6\n    self.assertEqual(self.solution.totalNQueens(6), 4)\nAssertionError: 0 != 4\n\n======================================================================\nFAIL: test_case_7 (__main__.TestNQueens.test_case_7)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 53, in test_case_7\n    self.assertEqual(self.solution.totalNQueens(7), 40)\nAssertionError: 0 != 40\n\n======================================================================\nFAIL: test_case_8 (__main__.TestNQueens.test_case_8)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 59, in test_case_8\n    self.assertEqual(self.solution.totalNQueens(8), 92)\nAssertionError: 0 != 92\n\n======================================================================\nFAIL: test_case_9 (__main__.TestNQueens.test_case_9)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\Serge\\Desktop\\GPT-Testing\\DataSets\\DataSet-Old\\LeetCodeTasks - Testing\\Tests\\52_n-queens-ii\\test.py\", line 65, in test_case_9\n    self.assertEqual(self.solution.totalNQueens(9), 352)\nAssertionError: 0 != 352\n\n----------------------------------------------------------------------\nRan 9 tests in 5.893s\n\nFAILED (failures=7)\n",
    "returncode": 1
}